<?php
//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'sample-extension/1.0.0',
	array(
		// Identification
		//
		'label' => 'User Request Access Level',
		'category' => 'business',

		// Setup
		//
		'dependencies' => array(
			'itop-service-mgmt/3.2.0' // ServiceSubcategory is defined here
		),
		'mandatory' => false,
		'visible' => true,

		// Components
		//
		'datamodel' => array(
			'model.sample-extension.php', // Contains the PHP code generated by the "compilation" of datamodel.sample-extension.xml
		),
		
		'routes' => array(
			'ajax.get_access_level' => array(
				'script' => 'ajax/get_access_level.php',
			),
		),

		'webservice' => array(),

		'dictionary' => array(
			'en.dict.sample-extension.php',
		),

		'data.struct' => array(
			// add your 'structure' definition XML files here,
		),
		'data.sample' => array(
			// add your sample data XML files here,
		),

		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any 

		// Default settings
		//
		'settings' => array(
			// Module specific settings go here, if any
		),
	)
);
